name: Docker Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract tag from ref
      id: extract_tag
      run: echo "::set-output name=TAG::$(echo ${GITHUB_REF#refs/tags/})"

    - name: Build and push Protobuf Exporter Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./images/protobuf-exporter/
        file: ./images/protobuf-exporter/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/protobuf-exporter:${{ steps.extract_tag.outputs.TAG }}

    - name: Build and push NGINX Ingress Controller Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./images/controller/
        file: ./images/controller/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/controller:${{ steps.extract_tag.outputs.TAG }}
        build-args: |
          TAG=${{ steps.extract_tag.outputs.TAG }}
